command:
  - python
  - -m
  - ppo_vmap.ppo
  - ${args}
name: big-ppo-sweep-discretize-actions
method: grid
metric:
  name: episode/return
  goal: maximize

parameters:
  # --- Fixed Parameters —
  total_timesteps:
    value: 100663296 # 2^25 *3
  wandb_entity:
    value: flair
  wandb_project:
    value: big-ppo-sweep
  use_wandb:
    value: True

  # --- Experiment Configuration ---
  env_name:
    values:
      - gymnax::MountainCarContinuous-v0
      - gymnax::Pendulum-v1
      - gymnax::PointRobot-misc
      - gymnax::Reacher-misc
      - gymnax::Swimmer-misc
      - brax::ant
      - brax::halfcheetah
      - brax::hopper
      - brax::humanoid
      - brax::humanoidstandup
      - brax::inverted_double_pendulum
      - brax::inverted_pendulum
      - brax::pusher
      - brax::reacher
      - brax::walker2d
      - jumanji::MultiCVRP-v0
      - mujoco_playground::AcrobotSwingup
      - mujoco_playground::AcrobotSwingupSparse
      - mujoco_playground::AeroCubeRotateZAxis
      - mujoco_playground::AlohaHandOver
      - mujoco_playground::AlohaSinglePegInsertion
      - mujoco_playground::ApolloJoystickFlatTerrain
      - mujoco_playground::BallInCup
      - mujoco_playground::BarkourJoystick
      - mujoco_playground::BerkeleyHumanoidJoystickFlatTerrain
      - mujoco_playground::BerkeleyHumanoidJoystickRoughTerrain
      - mujoco_playground::CartpoleBalance
      - mujoco_playground::CartpoleBalanceSparse
      - mujoco_playground::CartpoleSwingup
      - mujoco_playground::CartpoleSwingupSparse
      - mujoco_playground::CheetahRun
      - mujoco_playground::FingerSpin
      - mujoco_playground::FingerTurnEasy
      - mujoco_playground::FingerTurnHard
      - mujoco_playground::FishSwim
      - mujoco_playground::G1JoystickFlatTerrain
      - mujoco_playground::G1JoystickRoughTerrain
      - mujoco_playground::Go1Footstand
      - mujoco_playground::Go1Getup
      - mujoco_playground::Go1Handstand
      - mujoco_playground::Go1JoystickFlatTerrain
      - mujoco_playground::Go1JoystickRoughTerrain
      - mujoco_playground::H1InplaceGaitTracking
      - mujoco_playground::H1JoystickGaitTracking
      - mujoco_playground::HopperHop
      - mujoco_playground::HopperStand
      - mujoco_playground::HumanoidRun
      - mujoco_playground::HumanoidStand
      - mujoco_playground::HumanoidWalk
      - mujoco_playground::LeapCubeReorient
      - mujoco_playground::LeapCubeRotateZAxis
      - mujoco_playground::Op3Joystick
      - mujoco_playground::PandaOpenCabinet
      - mujoco_playground::PandaPickCube
      - mujoco_playground::PandaPickCubeCartesian
      - mujoco_playground::PandaPickCubeOrientation
      - mujoco_playground::PandaRobotiqPushCube
      - mujoco_playground::PendulumSwingup
      - mujoco_playground::PointMass
      - mujoco_playground::ReacherEasy
      - mujoco_playground::ReacherHard
      - mujoco_playground::SpotFlatTerrainJoystick
      - mujoco_playground::SpotGetup
      - mujoco_playground::SpotJoystickGaitTracking
      - mujoco_playground::SwimmerSwimmer6
      - mujoco_playground::T1JoystickFlatTerrain
      - mujoco_playground::T1JoystickRoughTerrain
      - mujoco_playground::WalkerRun
      - mujoco_playground::WalkerStand
      - mujoco_playground::WalkerWalk
      - kinetix::s
      - kinetix::m
      - kinetix::l
  seed:
    value: 0
  num_envs:
    value: 1024
  num_steps:
    value: 64
  num_epochs:
    value: 4
  num_minibatches:
    value: 8
  policy_lr:
    value: 3e-4
  value_fn_lr:
    value: 1e-4
  policy_wd:
    value: 0.0001
  value_wd:
    value: 0.0001
  gamma:
    value: 0.99
  gae_lambda:
    value: 0.95
  entropy_coef:
    value: 0.01
  epsilon:
    value: 0.2
  normalize_observations:
    value: True
  normalize_rewards:
    value: False
  use_symlog:
    value: False
  layer_size:
    value: 256
  activation:
    value: tanh
  stagger_steps:
    value: 1
  pool_size:
    value: 16
  num_runs:
    value: 8
  num_checkpoints:
    value: 1
  log_dir:
    value: /scratch/s5e/jarek.s5e/runs
  optimizer:
    value: adamw
  anneal_lr:
    value: False
  adam_epsilon:
    value: 1e-5
  discretize_actions:
    value: True
